version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:15"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "@statamic/cms"
